import type { Metadata } from 'next';
import SkHeader from '@/components/shadcn/sk-header';
import SkSidebar from '@/components/shadcn/sk-sidebar';
import { Sidebar, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Menu, Search } from 'lucide-react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SidebarProvider>
			<div className="flex flex-col w-full">
				<SkHeader />
				<SkSidebar />
				<main>
					{children}
				</main>
			</div>
		</SidebarProvider>
	);
}
